name: Build Periodic Backup plugin

on: [push, pull_request]

jobs:
  build:
    name: Build on JDK ${{ matrix.jdk }}
    strategy:
      matrix:
        jdk: [ '11', '17' ] # Updated JDK versions
    runs-on: ubuntu-latest

    steps:
      - name: Sync Repository
        uses: actions/checkout@v4 # Updated to v4
        with:
          submodules: true
      - name: Cache local Maven repository
        uses: actions/cache@v4 # Updated to v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v4 # Updated to v4
        with:
          distribution: 'temurin' # AdoptOpenJDK is now Eclipse Temurin
          java-version: ${{ matrix.jdk }}
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify # Corrected step
